import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "@/app/page.module.css";
import { auth } from "@/auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function BeforeLoginLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const session = await auth();
  if (session?.user) {
    redirect("/home");
    return null;
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        {children} {modal}
      </body>
    </html>
  );
}
